// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package main

import (
	"exp-gin/internal/biz"
	"exp-gin/internal/conf"
	"exp-gin/internal/data"
	"exp-gin/internal/server"
	"exp-gin/internal/service"
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
)

// Injectors from wire.go:

// initApp init kratos application.
func initApp(confServer *conf.Server, confData *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	dataData, cleanup, err := data.NewData(confData, logger)
	if err != nil {
		return nil, nil, err
	}
	loginRepo := data.NewLoginRepo(dataData, logger)
	loginUsecase := biz.NewLoginUsecase(loginRepo, logger)
	loginService := service.NewLoginService(loginUsecase, logger)
	httpServer := server.NewHTTPServer(confServer, loginService, logger)
	userRepo := data.NewUserRepo(dataData, logger)
	userUsecase := biz.NewUserUsecase(userRepo)
	userService := service.NewUserService(userUsecase, logger)
	grpcServer := server.NewGRPCServer(confServer, userService, logger)
	app := newApp(logger, httpServer, grpcServer)
	return app, func() {
		cleanup()
	}, nil
}
